// vue/src/App.vue
<script>
export default {
  data() {
    return {
      itemInput: '',
      editInput: '',
      currentEditingItem: 0,
      editFormStyles: {
        display: 'none',
        opacity: "0"
      },
      listItems: [
        'Apple',
        'Google',
        'Microsoft'
      ]
    }
  },
  methods: {
    addItem() {
      if (this.itemInput == '') return;

      this.listItems.push(this.itemInput);
      this.itemInput = '';
    },
    deleteItem(index) {
      this.listItems.splice(index, 1);
    },
    editItem(index) {
      requestAnimationFrame(() => {
        this.editFormStyles.display = "flex";
        requestAnimationFrame(() => {
          this.editFormStyles.opacity = "1";
        });
      });
      

      this.editInput = this.listItems[index];
      this.currentEditingItem = index;
    },
    updateItem() {
      this.listItems[this.currentEditingItem] = this.editInput;
      this.closeEdit();
    },
    closeEdit() {
      this.editFormStyles.opacity = "0";
      setTimeout(() => {
          this.editFormStyles.display = "none";
          this.editInput = '';
      }, 200);
    }
  }
}
</script>

<template>
  <main class="container">
      <h1>ListApp</h1>
      <p>Add new items to the list.</p>
      <form id="form" @submit.prevent="addItem">
          <label for="input">New Item</label>
          <input type="text" id="input" autocomplete="off" v-model="itemInput">
          <button type="submit">Submit</button>
      </form>
      
      <ul id="list">
        <!-- ITEMS -->
        <li v-for="(item, index) in listItems">
          {{ item }}
          <button class="button-clear button-small button-green" @click="editItem(index)">Edit</button>
          <button class="button-clear button-small button-red" @click="deleteItem(index)">Delete</button>
        </li>
      </ul>
  </main>
  <form id="edit-form" v-bind:style="{ display: editFormStyles.display, opacity: editFormStyles.opacity }">
      <div id="edit-form-content">
          <label for="edit-input">Edit Item</label>
          <input type="text" id="edit-input" autocomplete="off"  v-model="editInput">
          <button @click="closeEdit()" type="button">Cancel</button>
          <button @click.prevent="updateItem()" type="submit">Save</button>
      </div>
  </form>
</template>

<style scoped>

</style>

// reactjs/src/App.js
import logo from './logo.svg';
import './App.css';
import { useState } from "react";

let currentEditingItem = 0;


function App() {

  let [listItems, setListItems] = useState([
    'Apple',
    'Google',
    'Microsoft'
  ]);
  let [showEditForm, setShowEditForm] = useState(false);
  let [itemInput, setItemInput] = useState('');
  let [editInput, setEditInput] = useState('');
  let [editFormClassName, setEditFormClassName] = useState('fadeIn');
  
  function printList() {
    //console.log(listItems.map((item) => item));
    return listItems.map((item, index) =>
      <li key={index}>
        { item }
        <button className="button-clear button-small button-green" onClick={(e) => editItem(index) }>Edit</button>
        <button className="button-clear button-small button-red" onClick={(e) => deleteItem(index) }>Delete</button>
      </li>
    );
  }

  function addItem(event) {
    event.preventDefault();
    if (itemInput == '') return;
    setListItems([...listItems, itemInput]);
    setItemInput('');
  }

  function deleteItem(index) {
    setListItems(listItems.filter((item, i) => i !== index));
  }

  function editItem(index) {
    setShowEditForm(true);
    
    setEditInput(listItems[index]);
    currentEditingItem = index;
    console.log(currentEditingItem);
  }

  function updateItem(event) {
    event.preventDefault();
    let newVal = listItems.slice();
    newVal[currentEditingItem] = editInput;
    setListItems(newVal);
    closeEditForm();
  }

  function closeEditForm() {
    setEditFormClassName('fadeOut');
    setTimeout(()=>{
      setShowEditForm(false);
      setEditFormClassName('fadeIn');
    }, 150);
  }

  function editForm() {
    if (showEditForm) {
      return (
        <form id="edit-form" onSubmit={updateItem} className={editFormClassName}>
          <div id="edit-form-content">
            <label htmlFor="edit-input">Edit Item</label>
            <input type="text" id="edit-input" autoComplete="off" value={editInput} onChange={(e) => setEditInput(e.target.value)}/>
            <button onClick={closeEditForm} type="button">Cancel</button>
            <button type="submit">Save</button>
          </div>
        </form>
      );
    }
    return;
  }

  return (
    <div className="App">
      <main className="container">
        <h1>ListApp</h1>
        <p>Add new items to the list.</p>
        <form id="form" onSubmit={addItem}>
          <label htmlFor="input">New Item</label>
          <input type="text" id="input" autoComplete="off" value={itemInput} onChange={(e) => setItemInput(e.target.value)}/><button type="submit">Submit</button>
        </form>        
        <ul id="list">
          { printList() }
        </ul>        
      </main>
      { editForm() }
    </div>
  );
}

export default App;
